<a href="https://colab.research.google.com/github/DmitryZ2000/Numpy_Matplotlib_Sclearn_lesson6_hw/blob/lesson6/06_%D0%9E%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D1%81_%D1%83%D1%87%D0%B8%D1%82%D0%B5%D0%BB%D0%B5%D0%BC_%D0%B2_Scikit_learn_home.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Задание 1**  
Импортируйте библиотеки pandas и numpy.  
Загрузите "fetch_california_housing" из встроенных наборов данных библиотеки sklearn..  
Разбейте эти датафреймы на тренировочные (X_train, y_train) и тестовые (X_test, y_test) с помощью функции train_test_split так, чтобы размер тестовой выборки
составлял 30% от всех данных, при этом аргумент random state должен быть равен 42.  
Создайте модель линейной регрессии под названием lr c помощью класса LinearRegression из модуля sklearn.linear_model.  
Обучите модель на тренировочных данных (используйте все признаки) и сделайте предсказание на тестовых.

In [52]:
import numpy as np
import pandas as pd

# from sklearn.datasets import load_boston
from sklearn.datasets import fetch_california_housing

In [53]:
housing = fetch_california_housing()
print(housing["DESCR"])

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [54]:
housing.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [55]:
data = housing["data"]
data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [56]:
feature_names = housing["feature_names"]
feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [57]:

# Название колонок должно быть непрерывно, чтобы писать housing.data, иначе housing['data']
# X = pd.DataFrame(housing.data, columns=housing.feature_names)
X = pd.DataFrame(data, columns=feature_names)
X.head(3)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24

In [58]:
target = housing["target"]

target[:10]

array([4.526, 3.585, 3.521, 3.413, 3.422, 2.697, 2.992, 2.414, 2.267,
       2.611])

In [59]:
y = pd.DataFrame(target, columns=["price"])
y.head(3)

price
0  4.526
1  3.585
2  3.521

In [60]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   price   20640 non-null  float64
dtypes: float64(1)
memory usage: 161.4 KB


In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [63]:
y_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6192 entries, 20046 to 5786
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   price   6192 non-null   float64
dtypes: float64(1)
memory usage: 96.8 KB


In [64]:
from sklearn.linear_model import LinearRegression

In [65]:
lr = LinearRegression()

In [66]:
lr.fit(X_train, y_train)

LinearRegression()

In [67]:
y_pred = lr.predict(X_test)

In [68]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred, y_test)

0.530567782476675

In [69]:
y_pred_ser = pd.Series(y_pred.flatten())
y_test_ser = y_test['price']

In [70]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_pred_ser, y_test_ser)

0.530567782476675

##**Задание 2**  
Создайте модель под названием model c помощью класса RandomForestRegressor из модуля sklearn.ensemble.  
Сделайте агрумент n_estimators равным 1000, max_depth должен быть равен 12 и random_state сделайте равным 42.  
Обучите модель на тренировочных данных аналогично тому, как вы обучали модель LinearRegression, но при этом в метод fit вместо датафрейма y_train поставьте y_train.values[:, 0], чтобы получить из датафрейма одномерный массив Numpy,
так как для класса RandomForestRegressor в данном методе для аргумента y предпочтительно применение массивов вместо датафрейма.  
Сделайте предсказание на тестовых данных и посчитайте R2. Сравните с результатом из предыдущего задания.  
Напишите в комментариях к коду, какая модель в данном случае работает лучше.

In [71]:
from sklearn.ensemble import RandomForestRegressor

In [72]:
model = RandomForestRegressor(n_estimators=1000, max_depth=12, random_state=42)

In [73]:
y_train.values[:, 0]
# y_train.values

array([1.938, 1.697, 2.598, ..., 2.221, 2.835, 3.25 ])

In [74]:
%%time
model.fit(X_train, y_train.values[:, 0])

CPU times: user 1min 14s, sys: 283 ms, total: 1min 14s
Wall time: 1min 14s


RandomForestRegressor(max_depth=12, n_estimators=1000, random_state=42)

CPU times: user 1min 27s, sys: 325 ms, total: 1min 28s
Wall time: 1min 28s

In [75]:
y_pred = model.predict(X_test)

In [76]:
y_pred

array([0.52846315, 0.80579117, 4.82722688, ..., 2.12948238, 1.44929626,
       2.09039503])

In [77]:
y_test

price
20046  0.47700
3024   0.45800
15663  5.00001
20484  2.18600
9814   2.78000
...        ...
17505  2.37500
13512  0.67300
10842  2.18400
16559  1.19400
5786   2.09800

[6192 rows x 1 columns]

In [78]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7945061536878142

##Вывод##

Модель RandomForestRegressor имеет гораздо более высокую точниость близкую к 0.8, в то время как модель линейной регресси имеют точность близкую к 50/50, что равносильно слепому угадванию.

##***Задание 3**  
Вызовите документацию для класса RandomForestRegressor, найдите информацию об атрибуте feature_importances_.  
С помощью этого атрибута найдите сумму всех показателей важности, установите, какие два признака показывают наибольшую важность.

In [79]:
# ?RandomForestRegressor

In [80]:
importances = model.feature_importances_
std = np.std([tree.feature_importances_ for tree in model.estimators_], axis=0)
std.sort()
std

array([0.00350066, 0.00364316, 0.00533879, 0.0074107 , 0.00942017,
       0.01055859, 0.01176029, 0.01209264])

In [81]:
# сумму всех показателей важности
std.sum()

0.06372500569594888

In [82]:
# два признака показывают наибольшую важность.
std[-1], std[-2]

(0.012092644102912085, 0.011760285005273072)

##***Задание 4**  
В этом задании мы будем работать с датасетом, с которым мы уже знакомы по домашнему заданию по библиотеке Matplotlib, это датасет Credit Card Fraud Detection.Для этого датасета мы будем решать задачу классификации - будем определять,какие из транзакции по кредитной карте являются мошенническими.Данный датасет сильно несбалансирован (так как случаи мошенничества относительно редки),так что применение метрики accuracy не принесет пользы и не поможет выбрать лучшую модель.Мы будем вычислять AUC, то есть площадь под кривой ROC.  
Импортируйте из соответствующих модулей RandomForestClassifier, GridSearchCV и train_test_split.  
Загрузите датасет creditcard.csv и создайте датафрейм df.  
С помощью метода value_counts с аргументом normalize=True убедитесь в том, что выборка несбалансирована. Используя метод info, проверьте, все ли столбцы содержат числовые данные и нет или в них пропусков.Примените следующую настройку, чтобы можно было просматривать все столбцы датафрейма:  

**pd.options.display.max_columns = 100.**

In [ ]:
# Данную задачу сделаю позже